/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminDatasetRouteImport } from './routes/_authenticated/admin/dataset'
import { Route as AuthenticatedAdminHotspotsRouteImport } from './routes/_authenticated/admin/hotspots'
import { Route as AuthenticatedAdminMapRouteImport } from './routes/_authenticated/admin/map'
import { Route as AuthenticatedAdminRoutesRouteImport } from './routes/_authenticated/admin/routes'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminWorkersRouteImport } from './routes/_authenticated/admin/workers'
import { Route as AuthenticatedCitizenDashboardRouteImport } from './routes/_authenticated/citizen/dashboard'
import { Route as AuthenticatedCitizenProfileRouteImport } from './routes/_authenticated/citizen/profile'
import { Route as AuthenticatedCitizenReportRouteImport } from './routes/_authenticated/citizen/report'
import { Route as AuthenticatedWorkerDashboardRouteImport } from './routes/_authenticated/worker/dashboard'
import { Route as AuthenticatedWorkerProfileRouteImport } from './routes/_authenticated/worker/profile'
import { Route as AuthenticatedWorkerRoutesRouteImport } from './routes/_authenticated/worker/routes'
import { Route as AuthenticatedAdminComplaintsIndexRouteImport } from './routes/_authenticated/admin/complaints.index'
import { Route as AuthenticatedAdminComplaintsIdRouteImport } from './routes/_authenticated/admin/complaints.$id'
import { Route as AuthenticatedCitizenComplaintsIndexRouteImport } from './routes/_authenticated/citizen/complaints.index'
import { Route as AuthenticatedCitizenComplaintsIdRouteImport } from './routes/_authenticated/citizen/complaints.$id'
import { Route as AuthenticatedWorkerTasksIndexRouteImport } from './routes/_authenticated/worker/tasks.index'
import { Route as AuthenticatedWorkerTasksIdRouteImport } from './routes/_authenticated/worker/tasks.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDatasetRoute =
  AuthenticatedAdminDatasetRouteImport.update({
    id: '/admin/dataset',
    path: '/admin/dataset',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHotspotsRoute =
  AuthenticatedAdminHotspotsRouteImport.update({
    id: '/admin/hotspots',
    path: '/admin/hotspots',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMapRoute = AuthenticatedAdminMapRouteImport.update({
  id: '/admin/map',
  path: '/admin/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoutesRoute =
  AuthenticatedAdminRoutesRouteImport.update({
    id: '/admin/routes',
    path: '/admin/routes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminWorkersRoute =
  AuthenticatedAdminWorkersRouteImport.update({
    id: '/admin/workers',
    path: '/admin/workers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCitizenDashboardRoute =
  AuthenticatedCitizenDashboardRouteImport.update({
    id: '/citizen/dashboard',
    path: '/citizen/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCitizenProfileRoute =
  AuthenticatedCitizenProfileRouteImport.update({
    id: '/citizen/profile',
    path: '/citizen/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCitizenReportRoute =
  AuthenticatedCitizenReportRouteImport.update({
    id: '/citizen/report',
    path: '/citizen/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkerDashboardRoute =
  AuthenticatedWorkerDashboardRouteImport.update({
    id: '/worker/dashboard',
    path: '/worker/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkerProfileRoute =
  AuthenticatedWorkerProfileRouteImport.update({
    id: '/worker/profile',
    path: '/worker/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkerRoutesRoute =
  AuthenticatedWorkerRoutesRouteImport.update({
    id: '/worker/routes',
    path: '/worker/routes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplaintsIndexRoute =
  AuthenticatedAdminComplaintsIndexRouteImport.update({
    id: '/admin/complaints/',
    path: '/admin/complaints/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplaintsIdRoute =
  AuthenticatedAdminComplaintsIdRouteImport.update({
    id: '/admin/complaints/$id',
    path: '/admin/complaints/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCitizenComplaintsIndexRoute =
  AuthenticatedCitizenComplaintsIndexRouteImport.update({
    id: '/citizen/complaints/',
    path: '/citizen/complaints/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCitizenComplaintsIdRoute =
  AuthenticatedCitizenComplaintsIdRouteImport.update({
    id: '/citizen/complaints/$id',
    path: '/citizen/complaints/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkerTasksIndexRoute =
  AuthenticatedWorkerTasksIndexRouteImport.update({
    id: '/worker/tasks/',
    path: '/worker/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkerTasksIdRoute =
  AuthenticatedWorkerTasksIdRouteImport.update({
    id: '/worker/tasks/$id',
    path: '/worker/tasks/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/dataset': typeof AuthenticatedAdminDatasetRoute
  '/admin/hotspots': typeof AuthenticatedAdminHotspotsRoute
  '/admin/map': typeof AuthenticatedAdminMapRoute
  '/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/citizen/dashboard': typeof AuthenticatedCitizenDashboardRoute
  '/citizen/profile': typeof AuthenticatedCitizenProfileRoute
  '/citizen/report': typeof AuthenticatedCitizenReportRoute
  '/worker/dashboard': typeof AuthenticatedWorkerDashboardRoute
  '/worker/profile': typeof AuthenticatedWorkerProfileRoute
  '/worker/routes': typeof AuthenticatedWorkerRoutesRoute
  '/admin/complaints/$id': typeof AuthenticatedAdminComplaintsIdRoute
  '/citizen/complaints/$id': typeof AuthenticatedCitizenComplaintsIdRoute
  '/worker/tasks/$id': typeof AuthenticatedWorkerTasksIdRoute
  '/admin/complaints/': typeof AuthenticatedAdminComplaintsIndexRoute
  '/citizen/complaints/': typeof AuthenticatedCitizenComplaintsIndexRoute
  '/worker/tasks/': typeof AuthenticatedWorkerTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/dataset': typeof AuthenticatedAdminDatasetRoute
  '/admin/hotspots': typeof AuthenticatedAdminHotspotsRoute
  '/admin/map': typeof AuthenticatedAdminMapRoute
  '/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/citizen/dashboard': typeof AuthenticatedCitizenDashboardRoute
  '/citizen/profile': typeof AuthenticatedCitizenProfileRoute
  '/citizen/report': typeof AuthenticatedCitizenReportRoute
  '/worker/dashboard': typeof AuthenticatedWorkerDashboardRoute
  '/worker/profile': typeof AuthenticatedWorkerProfileRoute
  '/worker/routes': typeof AuthenticatedWorkerRoutesRoute
  '/admin/complaints/$id': typeof AuthenticatedAdminComplaintsIdRoute
  '/citizen/complaints/$id': typeof AuthenticatedCitizenComplaintsIdRoute
  '/worker/tasks/$id': typeof AuthenticatedWorkerTasksIdRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsIndexRoute
  '/citizen/complaints': typeof AuthenticatedCitizenComplaintsIndexRoute
  '/worker/tasks': typeof AuthenticatedWorkerTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/dataset': typeof AuthenticatedAdminDatasetRoute
  '/_authenticated/admin/hotspots': typeof AuthenticatedAdminHotspotsRoute
  '/_authenticated/admin/map': typeof AuthenticatedAdminMapRoute
  '/_authenticated/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/_authenticated/citizen/dashboard': typeof AuthenticatedCitizenDashboardRoute
  '/_authenticated/citizen/profile': typeof AuthenticatedCitizenProfileRoute
  '/_authenticated/citizen/report': typeof AuthenticatedCitizenReportRoute
  '/_authenticated/worker/dashboard': typeof AuthenticatedWorkerDashboardRoute
  '/_authenticated/worker/profile': typeof AuthenticatedWorkerProfileRoute
  '/_authenticated/worker/routes': typeof AuthenticatedWorkerRoutesRoute
  '/_authenticated/admin/complaints/$id': typeof AuthenticatedAdminComplaintsIdRoute
  '/_authenticated/citizen/complaints/$id': typeof AuthenticatedCitizenComplaintsIdRoute
  '/_authenticated/worker/tasks/$id': typeof AuthenticatedWorkerTasksIdRoute
  '/_authenticated/admin/complaints/': typeof AuthenticatedAdminComplaintsIndexRoute
  '/_authenticated/citizen/complaints/': typeof AuthenticatedCitizenComplaintsIndexRoute
  '/_authenticated/worker/tasks/': typeof AuthenticatedWorkerTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/unauthorized'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/dataset'
    | '/admin/hotspots'
    | '/admin/map'
    | '/admin/routes'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/workers'
    | '/citizen/dashboard'
    | '/citizen/profile'
    | '/citizen/report'
    | '/worker/dashboard'
    | '/worker/profile'
    | '/worker/routes'
    | '/admin/complaints/$id'
    | '/citizen/complaints/$id'
    | '/worker/tasks/$id'
    | '/admin/complaints/'
    | '/citizen/complaints/'
    | '/worker/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/unauthorized'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/dataset'
    | '/admin/hotspots'
    | '/admin/map'
    | '/admin/routes'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/workers'
    | '/citizen/dashboard'
    | '/citizen/profile'
    | '/citizen/report'
    | '/worker/dashboard'
    | '/worker/profile'
    | '/worker/routes'
    | '/admin/complaints/$id'
    | '/citizen/complaints/$id'
    | '/worker/tasks/$id'
    | '/admin/complaints'
    | '/citizen/complaints'
    | '/worker/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/unauthorized'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/dataset'
    | '/_authenticated/admin/hotspots'
    | '/_authenticated/admin/map'
    | '/_authenticated/admin/routes'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/workers'
    | '/_authenticated/citizen/dashboard'
    | '/_authenticated/citizen/profile'
    | '/_authenticated/citizen/report'
    | '/_authenticated/worker/dashboard'
    | '/_authenticated/worker/profile'
    | '/_authenticated/worker/routes'
    | '/_authenticated/admin/complaints/$id'
    | '/_authenticated/citizen/complaints/$id'
    | '/_authenticated/worker/tasks/$id'
    | '/_authenticated/admin/complaints/'
    | '/_authenticated/citizen/complaints/'
    | '/_authenticated/worker/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dataset': {
      id: '/_authenticated/admin/dataset'
      path: '/admin/dataset'
      fullPath: '/admin/dataset'
      preLoaderRoute: typeof AuthenticatedAdminDatasetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/hotspots': {
      id: '/_authenticated/admin/hotspots'
      path: '/admin/hotspots'
      fullPath: '/admin/hotspots'
      preLoaderRoute: typeof AuthenticatedAdminHotspotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/map': {
      id: '/_authenticated/admin/map'
      path: '/admin/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AuthenticatedAdminMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/routes': {
      id: '/_authenticated/admin/routes'
      path: '/admin/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AuthenticatedAdminRoutesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/workers': {
      id: '/_authenticated/admin/workers'
      path: '/admin/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AuthenticatedAdminWorkersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen/dashboard': {
      id: '/_authenticated/citizen/dashboard'
      path: '/citizen/dashboard'
      fullPath: '/citizen/dashboard'
      preLoaderRoute: typeof AuthenticatedCitizenDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen/profile': {
      id: '/_authenticated/citizen/profile'
      path: '/citizen/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof AuthenticatedCitizenProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen/report': {
      id: '/_authenticated/citizen/report'
      path: '/citizen/report'
      fullPath: '/citizen/report'
      preLoaderRoute: typeof AuthenticatedCitizenReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/dashboard': {
      id: '/_authenticated/worker/dashboard'
      path: '/worker/dashboard'
      fullPath: '/worker/dashboard'
      preLoaderRoute: typeof AuthenticatedWorkerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/profile': {
      id: '/_authenticated/worker/profile'
      path: '/worker/profile'
      fullPath: '/worker/profile'
      preLoaderRoute: typeof AuthenticatedWorkerProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/routes': {
      id: '/_authenticated/worker/routes'
      path: '/worker/routes'
      fullPath: '/worker/routes'
      preLoaderRoute: typeof AuthenticatedWorkerRoutesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/complaints/': {
      id: '/_authenticated/admin/complaints/'
      path: '/admin/complaints'
      fullPath: '/admin/complaints/'
      preLoaderRoute: typeof AuthenticatedAdminComplaintsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/complaints/$id': {
      id: '/_authenticated/admin/complaints/$id'
      path: '/admin/complaints/$id'
      fullPath: '/admin/complaints/$id'
      preLoaderRoute: typeof AuthenticatedAdminComplaintsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen/complaints/': {
      id: '/_authenticated/citizen/complaints/'
      path: '/citizen/complaints'
      fullPath: '/citizen/complaints/'
      preLoaderRoute: typeof AuthenticatedCitizenComplaintsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen/complaints/$id': {
      id: '/_authenticated/citizen/complaints/$id'
      path: '/citizen/complaints/$id'
      fullPath: '/citizen/complaints/$id'
      preLoaderRoute: typeof AuthenticatedCitizenComplaintsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/tasks/': {
      id: '/_authenticated/worker/tasks/'
      path: '/worker/tasks'
      fullPath: '/worker/tasks/'
      preLoaderRoute: typeof AuthenticatedWorkerTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/tasks/$id': {
      id: '/_authenticated/worker/tasks/$id'
      path: '/worker/tasks/$id'
      fullPath: '/worker/tasks/$id'
      preLoaderRoute: typeof AuthenticatedWorkerTasksIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDatasetRoute: typeof AuthenticatedAdminDatasetRoute
  AuthenticatedAdminHotspotsRoute: typeof AuthenticatedAdminHotspotsRoute
  AuthenticatedAdminMapRoute: typeof AuthenticatedAdminMapRoute
  AuthenticatedAdminRoutesRoute: typeof AuthenticatedAdminRoutesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWorkersRoute: typeof AuthenticatedAdminWorkersRoute
  AuthenticatedCitizenDashboardRoute: typeof AuthenticatedCitizenDashboardRoute
  AuthenticatedCitizenProfileRoute: typeof AuthenticatedCitizenProfileRoute
  AuthenticatedCitizenReportRoute: typeof AuthenticatedCitizenReportRoute
  AuthenticatedWorkerDashboardRoute: typeof AuthenticatedWorkerDashboardRoute
  AuthenticatedWorkerProfileRoute: typeof AuthenticatedWorkerProfileRoute
  AuthenticatedWorkerRoutesRoute: typeof AuthenticatedWorkerRoutesRoute
  AuthenticatedAdminComplaintsIdRoute: typeof AuthenticatedAdminComplaintsIdRoute
  AuthenticatedCitizenComplaintsIdRoute: typeof AuthenticatedCitizenComplaintsIdRoute
  AuthenticatedWorkerTasksIdRoute: typeof AuthenticatedWorkerTasksIdRoute
  AuthenticatedAdminComplaintsIndexRoute: typeof AuthenticatedAdminComplaintsIndexRoute
  AuthenticatedCitizenComplaintsIndexRoute: typeof AuthenticatedCitizenComplaintsIndexRoute
  AuthenticatedWorkerTasksIndexRoute: typeof AuthenticatedWorkerTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDatasetRoute: AuthenticatedAdminDatasetRoute,
  AuthenticatedAdminHotspotsRoute: AuthenticatedAdminHotspotsRoute,
  AuthenticatedAdminMapRoute: AuthenticatedAdminMapRoute,
  AuthenticatedAdminRoutesRoute: AuthenticatedAdminRoutesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWorkersRoute: AuthenticatedAdminWorkersRoute,
  AuthenticatedCitizenDashboardRoute: AuthenticatedCitizenDashboardRoute,
  AuthenticatedCitizenProfileRoute: AuthenticatedCitizenProfileRoute,
  AuthenticatedCitizenReportRoute: AuthenticatedCitizenReportRoute,
  AuthenticatedWorkerDashboardRoute: AuthenticatedWorkerDashboardRoute,
  AuthenticatedWorkerProfileRoute: AuthenticatedWorkerProfileRoute,
  AuthenticatedWorkerRoutesRoute: AuthenticatedWorkerRoutesRoute,
  AuthenticatedAdminComplaintsIdRoute: AuthenticatedAdminComplaintsIdRoute,
  AuthenticatedCitizenComplaintsIdRoute: AuthenticatedCitizenComplaintsIdRoute,
  AuthenticatedWorkerTasksIdRoute: AuthenticatedWorkerTasksIdRoute,
  AuthenticatedAdminComplaintsIndexRoute:
    AuthenticatedAdminComplaintsIndexRoute,
  AuthenticatedCitizenComplaintsIndexRoute:
    AuthenticatedCitizenComplaintsIndexRoute,
  AuthenticatedWorkerTasksIndexRoute: AuthenticatedWorkerTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
